### ISSUE TITLE
Compatibility Issue, Deselect x Slot Cycler

### ISSUE THREAD

**Issue by 533kr** [Jolkert/deselect#2]
I'm filing this with both Slot Cycler and the Deselect mod since I'm not where exactly the failure occurs, but with both [Slot Cycler](https://modrinth.com/mod/slot-cycler) and Deselect installed, pressing the deselect keybind causes an immediate crash. It sounds like it's the same basic issue as the other closed bug report, but I'm on the most recent Deselect version for 1.02.1 (1.1.1) and it's still crashing.

The resulting crashlog calls out Slot Cycler specifically as follows, if it helps:
[crash-2024-09-14_16.02.15-client.txt](https://github.com/user-attachments/files/17003691/crash-2024-09-14_16.02.15-client.txt)

(As an aside, like my comrade from the other bug report, I have also been jonesing for a mod that does this exact thing, so your work is deeply appreciated!!)

**Comment by Jolkert** [comment]
Thanks for reporting! Just fixed in commit f7f9f79!

(Thank you for your support!)
